// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpk0JzzKebP5AVBQ7Y1Z6yzFRewnBl_WM',
    appId: '1:829450261780:web:0026054c562f23b5751e01',
    messagingSenderId: '829450261780',
    projectId: 'restaurant-database-4f3f3',
    authDomain: 'restaurant-database-4f3f3.firebaseapp.com',
    storageBucket: 'restaurant-database-4f3f3.appspot.com',
    measurementId: 'G-000XLSENGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0UG634QZgW8PwFP568sidWpvkeV_T4w8',
    appId: '1:829450261780:android:9ee97adb199332b1751e01',
    messagingSenderId: '829450261780',
    projectId: 'restaurant-database-4f3f3',
    storageBucket: 'restaurant-database-4f3f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZzK5GeybR6MHCUP2Rzn3iCvtk6wJPYLU',
    appId: '1:829450261780:ios:984b8ee363092531751e01',
    messagingSenderId: '829450261780',
    projectId: 'restaurant-database-4f3f3',
    storageBucket: 'restaurant-database-4f3f3.appspot.com',
    iosClientId: '829450261780-6g197mtg1eeqejitiltbo361bab90d5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.emptyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZzK5GeybR6MHCUP2Rzn3iCvtk6wJPYLU',
    appId: '1:829450261780:ios:984b8ee363092531751e01',
    messagingSenderId: '829450261780',
    projectId: 'restaurant-database-4f3f3',
    storageBucket: 'restaurant-database-4f3f3.appspot.com',
    iosClientId: '829450261780-6g197mtg1eeqejitiltbo361bab90d5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.emptyProject',
  );
}
